-- ============================================================================
-- BISWAJIT POWER HUB — Supabase schema
-- Run in the Supabase SQL editor. Safe to re-run (uses IF NOT EXISTS).
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- SCOOTERS (catalog / inventory)
-- ---------------------------------------------------------------------------
create table if not exists public.scooters (
  id                text primary key,
  name              text not null,
  brand             text default 'PowerHub',
  tagline           text,
  price             numeric not null default 0,
  hue               text default 'blue',
  images            jsonb default '[]'::jsonb,
  battery_type      text,
  battery_capacity  text,
  range_km          numeric default 0,
  real_range_factor numeric default 0.83,
  top_speed         numeric default 25,
  charging_time     text,
  warranty          text,
  battery_warranty  text,
  motor             text,
  weight            text,
  load_capacity     text,
  colors            jsonb default '[]'::jsonb,
  no_licence        boolean default true,
  no_registration   boolean default true,
  stock_status      text default 'in_stock',
  featured          boolean default false,
  description       text,
  features          jsonb default '[]'::jsonb,
  benefits          jsonb default '[]'::jsonb,
  variants          jsonb default '[]'::jsonb,
  created_at        timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- ACCESSORIES (parts & add-ons catalog)
-- ---------------------------------------------------------------------------
create table if not exists public.accessories (
  id              text primary key,
  name            text not null,
  category        text not null default 'Other',
  price           numeric not null default 0,
  hue             text default 'teal',
  images          jsonb default '[]'::jsonb,
  description     text,
  compatibility   text,
  stock_status    text default 'in_stock',
  featured        boolean default false,
  created_at      timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- REVIEWS
-- ---------------------------------------------------------------------------
create table if not exists public.reviews (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  rating      int not null check (rating between 1 and 5),
  review      text not null,
  scooter     text,
  photo_url   text,
  status      text not null default 'pending', -- pending | approved | rejected | hidden
  featured    boolean default false,
  created_at  timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- CALLBACK REQUESTS
-- ---------------------------------------------------------------------------
create table if not exists public.callbacks (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  phone       text not null,
  visitor_id  text,
  handled     boolean default false,
  created_at  timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- TEST RIDE REQUESTS
-- ---------------------------------------------------------------------------
create table if not exists public.test_rides (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  phone           text not null,
  preferred_date  date,
  preferred_time  text,
  scooter         text,
  scooter_id      text,
  visitor_id      text,
  status          text default 'requested',
  created_at      timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- CONTACT MESSAGES
-- ---------------------------------------------------------------------------
create table if not exists public.contact_messages (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  phone       text not null,
  email       text,
  message     text not null,
  visitor_id  text,
  created_at  timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- LEAD EVENTS (raw interaction stream)
-- ---------------------------------------------------------------------------
create table if not exists public.lead_events (
  id          bigint generated by default as identity primary key,
  visitor_id  text,
  event_type  text not null,
  meta        jsonb default '{}'::jsonb,
  created_at  timestamptz default now()
);
create index if not exists lead_events_visitor_idx on public.lead_events (visitor_id);
create index if not exists lead_events_type_idx on public.lead_events (event_type);

-- ---------------------------------------------------------------------------
-- LEADS (aggregated, scored — keyed by visitor_id)
-- ---------------------------------------------------------------------------
create table if not exists public.leads (
  id                  uuid primary key default gen_random_uuid(),
  visitor_id          text unique,
  name                text,
  phone               text,
  last_source         text,
  interested_scooter  text,
  score               int default 0,
  classification      text default 'cold', -- hot | warm | cold
  status              text default 'new',  -- new | contacted | follow_up | converted | lost
  notes               text,
  created_at          timestamptz default now(),
  updated_at          timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- FINANCE SETTINGS (single row)
-- ---------------------------------------------------------------------------
create table if not exists public.finance_settings (
  id                    int primary key default 1,
  interest_rate         numeric default 12,
  down_payment_pct      numeric default 20,
  tenure_options        jsonb default '[6,12,18,24,36]'::jsonb,
  default_tenure        int default 12,
  min_down_payment_pct  numeric default 10,
  max_down_payment_pct  numeric default 60,
  file_charges          numeric default 2500,
  petrol_price_per_litre numeric default 110,
  petrol_mileage_km_per_litre numeric default 40,
  promo                 jsonb default '{"active":false,"label":""}'::jsonb,
  updated_at            timestamptz default now()
);
insert into public.finance_settings (id) values (1) on conflict (id) do nothing;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table public.scooters         enable row level security;
alter table public.accessories      enable row level security;
alter table public.reviews          enable row level security;
alter table public.callbacks        enable row level security;
alter table public.test_rides       enable row level security;
alter table public.contact_messages enable row level security;
alter table public.lead_events      enable row level security;
alter table public.leads            enable row level security;
alter table public.finance_settings enable row level security;

-- Public READ: scooters, finance settings, and approved reviews
create policy "public read scooters" on public.scooters
  for select using (true);

create policy "public read accessories" on public.accessories
  for select using (true);

create policy "public read finance" on public.finance_settings
  for select using (true);

create policy "public read approved reviews" on public.reviews
  for select using (status = 'approved');

-- Public INSERT: lead capture forms + events (anon can submit, not read)
create policy "anon insert reviews" on public.reviews
  for insert to anon
  with check (status = 'pending' and featured = false and rating between 1 and 5);
create policy "anon insert callbacks" on public.callbacks       for insert with check (true);
create policy "anon insert testrides" on public.test_rides      for insert with check (true);
create policy "anon insert contact"   on public.contact_messages for insert with check (true);
create policy "anon insert events"    on public.lead_events     for insert with check (true);
-- Leads: anon upsert via upsert_lead() RPC only (see functions below)

-- Authenticated (admin) FULL ACCESS to everything
create policy "auth all scooters"  on public.scooters          for all to authenticated using (true) with check (true);
create policy "auth all accessories" on public.accessories     for all to authenticated using (true) with check (true);
create policy "auth all reviews"   on public.reviews           for all to authenticated using (true) with check (true);
create policy "auth all callbacks" on public.callbacks         for all to authenticated using (true) with check (true);
create policy "auth all testrides" on public.test_rides        for all to authenticated using (true) with check (true);
create policy "auth all contact"   on public.contact_messages  for all to authenticated using (true) with check (true);
create policy "auth all events"    on public.lead_events       for all to authenticated using (true) with check (true);
create policy "auth all leads"     on public.leads             for all to authenticated using (true) with check (true);
create policy "auth all finance"   on public.finance_settings  for all to authenticated using (true) with check (true);

-- ============================================================================
-- SECURITY DEFINER RPCs (public lead upsert + analytics read)
-- ============================================================================

create or replace function public.enforce_review_pending()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.status := 'pending';
    new.featured := false;
  end if;
  return new;
end;
$$;

drop trigger if exists reviews_force_pending on public.reviews;
create trigger reviews_force_pending
  before insert on public.reviews
  for each row execute function public.enforce_review_pending();

create or replace function public.upsert_lead(
  p_visitor_id text,
  p_name text,
  p_phone text,
  p_last_source text,
  p_interested_scooter text,
  p_score int,
  p_classification text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_visitor_id is null or length(trim(p_visitor_id)) = 0 then
    raise exception 'visitor_id required';
  end if;

  insert into public.leads (
    visitor_id, name, phone, last_source, interested_scooter,
    score, classification, updated_at
  )
  values (
    p_visitor_id, p_name, p_phone, p_last_source, p_interested_scooter,
    coalesce(p_score, 0), coalesce(p_classification, 'cold'), now()
  )
  on conflict (visitor_id) do update set
    name = coalesce(excluded.name, leads.name),
    phone = coalesce(excluded.phone, leads.phone),
    last_source = excluded.last_source,
    interested_scooter = coalesce(excluded.interested_scooter, leads.interested_scooter),
    score = greatest(coalesce(leads.score, 0), coalesce(excluded.score, 0)),
    classification = excluded.classification,
    updated_at = now();
end;
$$;

revoke all on function public.upsert_lead(text, text, text, text, text, int, text) from public;
grant execute on function public.upsert_lead(text, text, text, text, text, int, text) to anon, authenticated;

create or replace function public.get_analytics_events(p_limit int default 8000)
returns table (
  event_type text,
  meta jsonb,
  created_at timestamptz,
  visitor_id text
)
language sql
security definer
set search_path = public
stable
as $$
  select e.event_type, e.meta, e.created_at, e.visitor_id
  from public.lead_events e
  order by e.created_at desc
  limit least(greatest(coalesce(p_limit, 8000), 1), 10000);
$$;

revoke all on function public.get_analytics_events(int) from public;
grant execute on function public.get_analytics_events(int) to anon, authenticated;

