-- ============================================================================
-- BISWAJIT POWER HUB — Supabase schema
-- Run in the Supabase SQL editor. Safe to re-run (uses IF NOT EXISTS).
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- SCOOTERS (catalog / inventory)
-- ---------------------------------------------------------------------------
create table if not exists public.scooters (
  id                text primary key,
  name              text not null,
  brand             text default 'PowerHub',
  tagline           text,
  price             numeric not null default 0,
  hue               text default 'blue',
  images            jsonb default '[]'::jsonb,
  battery_type      text,
  battery_capacity  text,
  range_km          numeric default 0,
  real_range_factor numeric default 0.83,
  top_speed         numeric default 25,
  charging_time     text,
  warranty          text,
  motor             text,
  weight            text,
  load_capacity     text,
  colors            jsonb default '[]'::jsonb,
  no_licence        boolean default true,
  no_registration   boolean default true,
  stock_status      text default 'in_stock',
  featured          boolean default false,
  description       text,
  features          jsonb default '[]'::jsonb,
  benefits          jsonb default '[]'::jsonb,
  created_at        timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- REVIEWS
-- ---------------------------------------------------------------------------
create table if not exists public.reviews (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  rating      int not null check (rating between 1 and 5),
  review      text not null,
  scooter     text,
  photo_url   text,
  status      text not null default 'pending', -- pending | approved | rejected | hidden
  featured    boolean default false,
  created_at  timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- CALLBACK REQUESTS
-- ---------------------------------------------------------------------------
create table if not exists public.callbacks (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  phone       text not null,
  visitor_id  text,
  handled     boolean default false,
  created_at  timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- TEST RIDE REQUESTS
-- ---------------------------------------------------------------------------
create table if not exists public.test_rides (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  phone           text not null,
  preferred_date  date,
  preferred_time  text,
  scooter         text,
  scooter_id      text,
  visitor_id      text,
  status          text default 'requested',
  created_at      timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- CONTACT MESSAGES
-- ---------------------------------------------------------------------------
create table if not exists public.contact_messages (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  phone       text not null,
  email       text,
  message     text not null,
  visitor_id  text,
  created_at  timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- LEAD EVENTS (raw interaction stream)
-- ---------------------------------------------------------------------------
create table if not exists public.lead_events (
  id          bigint generated by default as identity primary key,
  visitor_id  text,
  event_type  text not null,
  meta        jsonb default '{}'::jsonb,
  created_at  timestamptz default now()
);
create index if not exists lead_events_visitor_idx on public.lead_events (visitor_id);
create index if not exists lead_events_type_idx on public.lead_events (event_type);

-- ---------------------------------------------------------------------------
-- LEADS (aggregated, scored — keyed by visitor_id)
-- ---------------------------------------------------------------------------
create table if not exists public.leads (
  id                  uuid primary key default gen_random_uuid(),
  visitor_id          text unique,
  name                text,
  phone               text,
  last_source         text,
  interested_scooter  text,
  score               int default 0,
  classification      text default 'cold', -- hot | warm | cold
  status              text default 'new',  -- new | contacted | follow_up | converted | lost
  notes               text,
  created_at          timestamptz default now(),
  updated_at          timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- FINANCE SETTINGS (single row)
-- ---------------------------------------------------------------------------
create table if not exists public.finance_settings (
  id                    int primary key default 1,
  interest_rate         numeric default 12,
  down_payment_pct      numeric default 20,
  tenure_options        jsonb default '[6,12,18,24,36]'::jsonb,
  default_tenure        int default 12,
  min_down_payment_pct  numeric default 10,
  max_down_payment_pct  numeric default 60,
  petrol_price_per_litre numeric default 110,
  petrol_mileage_km_per_litre numeric default 40,
  promo                 jsonb default '{"active":false,"label":""}'::jsonb,
  updated_at            timestamptz default now()
);
insert into public.finance_settings (id) values (1) on conflict (id) do nothing;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table public.scooters         enable row level security;
alter table public.reviews          enable row level security;
alter table public.callbacks        enable row level security;
alter table public.test_rides       enable row level security;
alter table public.contact_messages enable row level security;
alter table public.lead_events      enable row level security;
alter table public.leads            enable row level security;
alter table public.finance_settings enable row level security;

-- Public READ: scooters, finance settings, and approved reviews
create policy "public read scooters" on public.scooters
  for select using (true);

create policy "public read finance" on public.finance_settings
  for select using (true);

create policy "public read approved reviews" on public.reviews
  for select using (status = 'approved');

-- Public INSERT: lead capture forms + events (anon can submit, not read)
create policy "anon insert reviews"  on public.reviews          for insert with check (true);
create policy "anon insert callbacks" on public.callbacks       for insert with check (true);
create policy "anon insert testrides" on public.test_rides      for insert with check (true);
create policy "anon insert contact"   on public.contact_messages for insert with check (true);
create policy "anon insert events"    on public.lead_events     for insert with check (true);
create policy "anon upsert leads ins" on public.leads           for insert with check (true);
create policy "anon upsert leads upd" on public.leads           for update using (true) with check (true);

-- Authenticated (admin) FULL ACCESS to everything
create policy "auth all scooters"  on public.scooters          for all to authenticated using (true) with check (true);
create policy "auth all reviews"   on public.reviews           for all to authenticated using (true) with check (true);
create policy "auth all callbacks" on public.callbacks         for all to authenticated using (true) with check (true);
create policy "auth all testrides" on public.test_rides        for all to authenticated using (true) with check (true);
create policy "auth all contact"   on public.contact_messages  for all to authenticated using (true) with check (true);
create policy "auth all events"    on public.lead_events       for all to authenticated using (true) with check (true);
create policy "auth all leads"     on public.leads             for all to authenticated using (true) with check (true);
create policy "auth all finance"   on public.finance_settings  for all to authenticated using (true) with check (true);
